version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lanchonete-db
    environment:
      POSTGRES_DB: hamburgueria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: lanchonete-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/hamburgueria
      DB_USER: postgres
      DB_PASS: postgres
      SPRING_SQL_INIT_MODE: always
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION: "true"

  frontend:
    build: ./frontend
    container_name: lanchonete-ui
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: